# TalkShow Default Configuration
# This file provides default settings for TalkShow

# Parser settings
parser:
  # Default history directory (relative to project root)
  # history_directory: ".specstory/history"
  history_directory: "history"
  
  # File patterns to include
  include_patterns:
    - "*.md"
  
  # File patterns to exclude
  exclude_patterns:
    - "README.md"
    - ".*"

# Summarizer settings
summarizer:
  # Enable/disable summarization
  enabled: true
  
  # Rule-based summarizer settings
  rule:
    max_question_length: 20
    max_answer_length: 80
  
  # LLM summarizer settings
  llm:
    enabled: false  # Default to false for cost control
    provider: "moonshot"
    api_key: "xxxxxxxxxxxxx"
    model: "moonshot/kimi-k2-0711-preview"
    max_tokens: 150
    temperature: 0.3

# Storage settings
storage:
  # Default storage type: json or sqlite
  type: "json"
  
  # JSON storage settings
  json:
    # file_path: ".specstory/data/sessions.json"
    file_path: "data/sessions.json"
    backup_enabled: true
    backup_interval: "daily"
  
  # SQLite storage settings (for future use)
  sqlite:
    database_path: ".specstory/data/sessions.db"
    backup_enabled: true

# Web server settings
web:
  host: "127.0.0.1"
  port: 8000
  debug: false
  reload: true
  
  # CORS settings
  cors:
    enabled: true
    origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"

# CLI settings
cli:
  # Default output format
  output_format: "table"
  
  # Pagination settings
  page_size: 20
  
  # Date format for display
  date_format: "%Y-%m-%d %H:%M:%S"

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/talkshow.log"

# Project settings
project:
  name: "TalkShow Project"
  description: "Chat history analysis and visualization"