"""
TalkShow - Chat History Analysis and Visualization Tool

A tool for analyzing and visualizing chat history generated by SpecStory plugin.
"""

__version__ = "0.1.0"
__author__ = "TalkShow Team"
__description__ = "Chat History Analysis and Visualization Tool"

from .models.chat import ChatSession, QAPair, SessionMeta

__all__ = [
    "ChatSession",
    "QAPair", 
    "SessionMeta",
]