"""
TalkShow - Chat History Analysis and Visualization Tool

A tool for analyzing and visualizing chat history generated by SpecStory plugin.
"""

__version__ = "0.2.0"
__author__ = "TalkShow Team"
__description__ = "Chat History Analysis and Visualization Tool"

from .models.chat import ChatSession, QAPair, SessionMeta
from .parser.md_parser import MDParser
from .storage.json_storage import JSONStorage
from .summarizer.rule_summarizer import RuleSummarizer
from .summarizer.llm_summarizer import LLMSummarizer
from .config.config_manager import ConfigManager

__all__ = [
    "ChatSession",
    "QAPair", 
    "SessionMeta",
    "MDParser",
    "JSONStorage",
    "RuleSummarizer",
    "LLMSummarizer",
    "ConfigManager",
]